---
- name: Install K8 Master 
  hosts: kube-control1.sriauronet.local
  remote_user: k8admin
  become: yes
  become_method: sudo
  become_user: root

  vars_prompt: 
    - name: "pod_network_cidr"
      prompt: "Enter the Pod network CIDR, example: 172.16.0.0/24"
      private: no
    
    - name: "k8s_master_ip"
      prompt: "Enter the Apiserver advertise address, exampel: 10.1.1.21/24"
      private: no

    #https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
    - name: "pod_network_manifest_file"
      prompt: "Enter the Pod network menifest URL  "
      private: no

    #- name: "rbac_manifest_file"
    #  prompt: "Enter the RBAC manifest file URL "
    #  private: no

  tasks:

    - name: Intilizing Kubernetes Cluster
      command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ k8s_master_ip }}"
      run_once: true
      delegate_to: "{{ k8s_master_ip }}"
    - pause: seconds=30
    - name: Create directory for kube config.
      become_user: ansible
      become_method: sudo
      become: yes
      file: 
        path: /home/{{ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
    - name: Copy /etc/kubernetes/admin.conf to user's home directory /home/{{ ansible_user }}/.kube/config.
      become_user: root
      become_method: sudo
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
    - pause: seconds=10
    - name: Remove the cache directory.
      become_user: ansible
      become_method: sudo
      become: yes
      file: 
        path: /home/{{ ansible_user }}/.kube/cache
        state: absent
    - name: Create Pod Network & RBAC.
      become_user: ansible
      become_method: sudo
      become: yes
      command: "{{ item }}"
      with_items: 
        - kubectl apply -f {{ pod_network_manifest_file }}
      #  - kubectl apply -f {{ rbac_manifest_file }}
    - pause: seconds=30
    - name: Get the token for joining the nodes with Kuberentes master.
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
...