- name: Initialize Kubernetes Control node 
  hosts: controlNode1
  vars:
    cri_socket: unix:///var/run/cri-dockerd.sock  
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }} --cri-socket {{ cri_socket }}"
- name: Join worker nodes
  hosts: workerNodes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['kube-control1.sriauronet.local'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt