---
- name: "This is to test shell module on ansible version in ansible version 2.16"
  hosts: all
  become: true
  become_user: root
  vars:
    boot_entries: "/boot/loader/entries"
    ip_path: "/usr/sbin/ip"
  tasks:
  - name: "Print a random number from play hosts"
    shell: |
      set -eo pipefail
      set -u 
      echo $RANDOM
    args:
      executable: /bin/bash
    timeout: 300
    register: active_item
#    failed_when: boot_entries_ls.rc != 0
  - name: "Print the active_item"
    debug:
      msg: "{{ active_item.stdout | trim | int }}"
  - name: "Set this as a fact"
    ansible.builtin.set_fact:
      active_item_count: "{{ active_item.stdout | trim | int }}"
#  - name: Verify the variable type and value
#    ansible.builtin.debug:
#      msg: "Value is {{ active_item_count }} and its type is integer"
#    when: active_item_count | int is number
  - name: Add active_item_count from all the play hosts and calculate average
    ansible.builtin.debug:
      msg: >
        Total sum is {{ total_sum }} 
        Average is {{ total_sum | int / inventory_hostname_count | int }}
      vars:
        total_sum: "{{ ansible_play_hosts | map('extract', hostvars, 'active_item_count') | map('int') | sum }}"
        inventory_hostname_count: "{{ ansible_play_hosts | length }}"


  

