---
- name: Calculate active item counts and determine rebalance requirement across play hosts
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Get active_item as a random number from each host
      ansible.builtin.shell: |
        set -eo pipefail
        set -u
        echo $RANDOM
      args:
        executable: /bin/bash
      register: active_item
      changed_when: false

    - name: Set active_item as custom fact active_item_count
      ansible.builtin.set_fact:
        active_item_count: "{{ active_item.stdout | trim | int }}"

    - name: Calculate sum of active_item_count across all play hosts and compute average
      ansible.builtin.set_fact:
        total_sum: "{{ ansible_play_hosts | map('extract', hostvars, 'active_item_count') | map('int') | sum }}"
        average: "{{ (ansible_play_hosts | map('extract', hostvars, 'active_item_count') | map('int') | sum) / (ansible_play_hosts | length) | int }}"
      run_once: true

    - name: Calculate difference (rebalance_items) and determine rebalance_required
      ansible.builtin.set_fact:
        rebalance_items: "{{ (active_item_count | int) - (average | int) }}"
        rebalance_required: "{{ ((active_item_count | int) - (average | int)) > 300 }}"

    - name: Print debug info (Total sum, average, rebalance_items, rebalance_required)
      ansible.builtin.debug:
        msg:
          - "Total sum: {{ total_sum }}"
          - "Average: {{ average }}"
          - "Rebalance items: {{ rebalance_items }}"
          - "Rebalance required: {{ rebalance_required }}"
    - name: generate the rebalance command only when rebalance required is set to true.
      ansible.builtin.debug:
        msg: >
          Rebalance command: adhmon -rebal  <route name> <service name> {{ rebalance_items }} 300
      when: rebalance_required

    - name: List play hosts that have rebalance_required set to true
      ansible.builtin.debug:
        msg: >-
          {{
            ansible_play_hosts
            | map('extract', hostvars)
            | selectattr('rebalance_required', 'defined')
            | selectattr('rebalance_required', 'equalto', true)
            | map(attribute='inventory_hostname')
            | list
          }}
      run_once: true
