---
- name: "This is to test shell module on ansible version in ansible version 2.16"
  hosts: cos9
  become: true
  become_user: root
  vars:
    boot_entries: "/boot/loader/entries"
    ip_path: "/usr/sbin/ip"
  tasks:
  - name: "This is to test shell module on ansible version in ansible version 2.16"
    shell: |
      set -eo pipefail
      set -u 
      
      if [[ ! -x {{ ip_path|quote }} ]]; then
        echo "{{ ip_path }} not found" >&2
        exit 1
      fi
      
      {{ ip_path|quote }} addr show | grep ens33 -A4 | grep inet | awk '{ print $1, " : " ,$2}'
#    args:
#      executable: /bin/bash
#    timeout: 300
#    register: boot_entries_ls
#    failed_when: boot_entries_ls.rc != 0
  - name: "Print the entires"
    debug:
      msg: "{{ boot_entries_ls.stdout }}"
