apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp-billi
  ports:
  - port: 80
    targetPort: 80
    #valid nodePort range 32000 32767 
    nodePort: 30008
