---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
  labels:
    app: kuard
    version: "2"
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: kuard
      version: "2"
  template:
    metadata:
      name: kuard
      labels:
        app: kuard
        version: "2"
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:green
          ports:
            - containerPort: 8080

...
