---
- name: Demonstrate when command 
  hosts: list1
  tasks:
    - name: Reboot Redhat systems 
      debug:
        msg:  
          - "{{ ansible_facts['distribution'] }} "
          - "{{ ansible_facts['distribution_major_version'] }}"
      when: ansible_facts['os_family'] == "RedHat"

