---
- name : When demo
  hosts: all
  vars:
    supported_distros:
      - RedHat
      - CentOS
      - Fedora
  tasks:
    - name:  Install RH family specific packages 
      yum: 
        name: nginx
        state: present
      when: ansible_distribution in supported_distros

