---
- name: Loop Demonstration
  hosts: localhost
  vars:
    my_dict_list:
      - user_name: prabhat
        group: admin
        home_dir: /home/prabhat
      - user_name: priya
        group: admin
        home_dir: /home/priya
      - user_name: billi
        group: admin
        home_dir: /home/billi
      - user_name: john
        group: admin
        home_dir: /home/john
  tasks:
    - name: Loop through array of dictionary
      ansible.builtin.debug:
        msg: "{{ item.user_name }} : {{ item.group }} : {{ item.home_dir }}"
      loop: "{{ my_dict_list }}"
    - name: Loop though dictionary itslef
      ansible.builtin.debug:
        msg: "{{ item.key }} : {{ item.value }}"
      loop: "{{ my_dict | dict2items }}"
      vars:
        my_dict:
          user_name: prabhat
          group: admin
          home_dir: /home/prabhat
