---
- name: Looping over a list
  hosts: localhost
  vars:
    my_billi:
      - priya
      - billi
      - meow
  vars_files:
    - vars.yml
  tasks:
    - name: Print each item in the list
      debug:
        msg: "Showing {{ item }}"
      loop: "{{ my_list }}"
    - name: Another list
      debug:
        msg: "Another list {{ my_billi }}"
