apiVersion: v1
kind: Pod
metadata:
  name: initpod
  labels:
    name: init-container-demo
spec:
  containers:
    - name: after-init
      image: gcr.io/google-containers/busybox
      command: ['ssh', '-c', 'echo it is running!! && sleep 3600']
  initContainers:
    - name: init-myservice
      image: gcr.io/google-containers/busybox
      command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep2; done']
