apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-billi
spec:
  selector:
    matchLabels:
      app: myapp-billi
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp-billi
    spec:
      containers:
      - name: myapp
        image: nginx:1.8.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
