---
- name: Install httpd
  hosts: centos8-stream
  tasks:
    - name: Install package
      package:
        name: httpd
        state: present
    - name: Create an Index.html
      copy:
        content: 'Welcome to Billi Meow Server'
        dest: /var/www/html/index.html
    - name: Start the Service
      service:
        name: httpd
        state: started
        enabled: true
    - name: Open Firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: true
...
