---
- name: Test set facts
  hosts: node1.sriauronet.lan


  tasks:
    - name: Get Active Items
      ansible.builtin.shell:
        cmd: /home/prabhat/get_value.sh
      register: active_items
      changed_when: false

    - name: Print Active Items
      debug:
        var: active_items.stdout

    - name: Set Fact
      ansible.builtin.set_fact:
        active_item_count: "{{ active_items.stdout }}"
    - name: Set multiple custom facts
      ansible.builtin.set_fact:
        environment_type: "production"
        app_version: "1.4.2"

    - name: Print all host facts (including custom ones)
      ansible.builtin.debug:
        var: ansible_facts
