---
- name: Test set facts
  hosts: all


  tasks:
    - name: Get Active Items
      ansible.builtin.shell:
        cmd: /home/prabhat/get_value.sh
      register: active_items

    - name: Print Active Items
      debug:
        var: active_items