---
- name: Test set facts
  hosts: all


  tasks:
    - name: Get Active Items
      ansible.builtin.shell:
        cmd: /home/prabhat/get_value.sh
      register: active_items
      changed_when: false

    - name: Print Active Items
      debug:
        var: active_items.stdout

    - name: Set Fact
      set_fact:
        active_item_count: "{{ active_items.stdout }}"
    - name: Get All the active_items
      hosts: node1.sriauronet.lan
      debug:
        var: ansible_facts
