apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labes:
    app: nginx
spec: 
  containers: 
  - name:  

multilineString: | 
  this is a multi line string 
  this is the second line of multiline string 
  